### ISSUE TITLE
I just wanted to say

### ISSUE THREAD

**Issue by emre** [Eaykat/Python#1]
ADAMSIN.

<img src="https://media.giphy.com/media/ZX6NHzA9Fcddm/giphy.gif">

**Comment by hwclass** [comment]
Çok iyi!

![goodgood](https://cloud.githubusercontent.com/assets/3750931/12048394/839e01a4-aee3-11e5-99f6-410ad225f70d.jpeg)

**Comment by Eaykat** [comment]
Dark side!!
